---

plugins:
  - jest
  - babel
  - react
  - react-hooks

env:
  node: true
  jest: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:react/recommended'

settings:
  react:
    version: detect

rules:
  no-console: 0
  class-methods-use-this: 0
  import/no-unresolved: 0
  no-undef: 0
  react/prop-types: 0
  react/display-name: 0
  import/first: 0
  import/extensions: 0
  react-hooks/rules-of-hooks: 'error'
  react-hooks/exhaustive-deps: 'warn'
  no-restricted-syntax: 0
  object-curly-newline: 0
  react/no-render-return-value: 0
